accounts:
    type:     rest
    resource: AppBundle\Controller\REST\AccountController
    prefix: 'api'

accountSheets:
    type:     rest
    resource: AppBundle\Controller\REST\AccountSheetController
    prefix: 'api'

operation:
    type:     rest
    resource: AppBundle\Controller\REST\OperationController
    prefix: 'api'

fallback:
    path: /
    defaults: { _controller: AppBundle:Default:index, url: null }
    requirements:
        url: .*
