api:
    type:     annotation
    resource: "@AppBundle/Controller/REST"
    prefix: '/api'
app:
    path: /{req}
    defaults: { _controller: 'AppBundle:Default:index' }
    requirements:
        req: ".+"
fallback:
    path: /
    defaults: { _controller: 'AppBundle:Default:index' }
