AppBundle\Entity\Account:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
            - Type: string

AppBundle\Entity\AccountSheet:
    properties:
        name:
            - NotBlank: ~
            - Type: string

AppBundle\Entity\Operation:
    properties:
        type:
            - NotBlank: ~
            - Type: integer
        label:
            - NotBlank: ~
            - Type: string
        comment:
            - NotBlank: ~
            - Type: string
        montant:
            - NotBlank: ~
            - Type: float

AppBundle\Entity\Category:
    properties:
        label:
            - NotBlank: ~
            - Type: string
        description:
            - NotBlank: ~
            - Type: string
